version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./mysql:/var/lib/mysql

  wp:
    build: .
    environment:
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wp
    ports:
      - "80:80"
    links:
      - mysql
    volumes:
      - ./html:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=pass
    links:
      - mysql
    ports:
      - '8080:80'
    volumes:
      - /sessions
